tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/bundle"

brew "zsh"
brew "git"
brew "yarn"
brew "python3"
brew "coreutils"
brew "grep"
brew "mackup"
brew "mas"

cask "iterm2"
cask "visual-studio-code"
cask "slack"
cask "spotify"
cask "alfred"
cask "flux"
cask "sketch"
cask "brave-browser"
cask "font-fira-code"
cask "github"

mas "Spark", id: 1176895641
mas "Todoist", id: 585829637
mas "Magnet", id: 441258766